export const FEATURES = {
  AGENTS: false,
  MARKETPLACE: false,
  PROMPTS: false,
  SKILLS: true,
  MCP: false,
  PRESETS: false,
  SEARCH: false,
  SHARE: false,
  PLUGINS: false,
  TWO_FACTOR: false,
  TAGS: false,
  ARTIFACTS: false,
  ANONYMIZATION: true,
  AGENT_CHAT: true,
};
