const BASE = '/mdp/ai-safe';

export const MDP_ENDPOINTS = {
  chat: `${BASE}/chat`,
  chatModels: `${BASE}/chat-models`,
  detect: `${BASE}/detect`,
  anonymize: `${BASE}/anonymize`,
  deidentify: `${BASE}/deidentify`,
  upload: `${BASE}/upload`,
  voice: `${BASE}/voice`,
  history: `${BASE}/history`,
  agentChat: `${BASE}/agent/chat`,
  sessionRename: `${BASE}/session/rename`,
  sessionDelete: `${BASE}/session/delete`,
  sessionTokenUsage: `${BASE}/session/get-token-usage`,
  anonymizeFile: `${BASE}/anonymize-file`,
  anonymisedUpload: `${BASE}/anonymised-upload`,
  generateImage: `${BASE}/generate-image`,
  image: `${BASE}/image`,
  setModelParams: `${BASE}/set-model-params`,
  getModelParams: `${BASE}/get-model-params`,
  health: `${BASE}/health`,
  supportedFiles: `${BASE}/supported-files`,
  billingDetails: `${BASE}/billing-details`,
  premadePrompts: `${BASE}/premade-prompts`,
  documentTemplates: `${BASE}/document-templates`,
  artifacts: `${BASE}/artifacts`,
};
